language: java
jdk:
  - oraclejdk7
env:
  - TERM=dumb

install:
  - ./gradlew assemble --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - ./gradlew jacocoTestReport coveralls --stacktrace